### ISSUE TITLE
Account management production TODO

### ISSUE THREAD

**Issue by md-abdul-halim-rafi** [HypeScout/project-management#19]
### Turtle backend
- [x] New env variable `RABBIT_MQ_URL`
- [x] Check the usage of `is_searchable` while searching or filtering
- [x] Check is army deleted at search summary job
- [x] Synchronize scheme of the army in the database with const

### DB Scripts
- [x] update `army` table `scheme` to all uppercase
- [x] update `army` table `is_deleted = true` where `status = 9`;
- [x] update `army` table `email_verified = true` where `scheme != "OWN"`
- [x] update `army` table `email_verified = true` where `status != PENDING_PROFILE`
- [x] update `agent` table `email_verified = true` where `status = 1`;
- [x] Clone HypeSocial username to `hype_dev` DB 
- [x] Insert profile setting for `army` & `agent`

### Influencer front
- [x] Removed the react-google-login package, so must integrate the new google login mechanism for YouTube connect
